{print} = require 'sys'
{exec, spawn} = require 'child_process'

task 'build', 'Build project from src.coffee/*.coffee to src/*.js', ->
  exec 'coffee --compile --output src/ src.coffee/', (err, stdout, stderr) ->
    throw err if err
    console.log stdout + stderr

task 'watch', 'Watch src.coffee/ for changes', ->
    coffee = spawn 'coffee', ['-w', '-c', '-o', 'src', 'src.coffee']
    coffee.stderr.on 'data', (data) ->
      process.stderr.write data.toString()
    coffee.stdout.on 'data', (data) ->
      print data.toString()
